/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package engine.debugging.entityeditor.gui;

import engine.debugging.entityeditor.gui.tree.EntityPanel;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author finne
 */
public class MainFrame extends javax.swing.JFrame {

   
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        textureFileChooser = new javax.swing.JFileChooser();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        entityPanel1 = new EntityPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        positionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        position_x = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        position_y = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        position_z = new javax.swing.JTextField();
        rotationPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rotation_x = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rotation_y = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rotation_z = new javax.swing.JTextField();
        rotationPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        scale_x = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        scale_y = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        scale_z = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        texture_panel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        colormap_file = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        normalmap_file = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lightmap_file = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        bumpmap_file = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        textureFileChooser.setDialogTitle("Choose Texture");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG Images", "png", "png");
        textureFileChooser.setFileFilter(filter);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar2.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton2);

        jButton3.setText("jButton3");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton3);

        jButton4.setText("jButton4");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton4);

        jButton5.setText("jButton5");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton5);

        jButton6.setText("jButton6");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton6);

        jButton7.setText("jButton7");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton7);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 489));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(entityPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel5.setOpaque(false);

        jRadioButton1.setText("keyframed");

        positionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Position"));
        positionPanel.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("X");
        jLabel1.setOpaque(true);
        positionPanel.add(jLabel1);

        position_x.setText("0");
        position_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position_xActionPerformed(evt);
            }
        });
        positionPanel.add(position_x);

        jLabel2.setText("Y");
        jLabel2.setOpaque(true);
        positionPanel.add(jLabel2);

        position_y.setText("0");
        positionPanel.add(position_y);

        jLabel3.setText("Z");
        jLabel3.setOpaque(true);
        positionPanel.add(jLabel3);

        position_z.setText("0");
        positionPanel.add(position_z);

        rotationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Rotation"));
        rotationPanel.setLayout(new java.awt.GridLayout(3, 2));

        jLabel4.setText("X");
        jLabel4.setOpaque(true);
        rotationPanel.add(jLabel4);

        rotation_x.setText("0");
        rotationPanel.add(rotation_x);

        jLabel5.setText("Y");
        jLabel5.setOpaque(true);
        rotationPanel.add(jLabel5);

        rotation_y.setText("0");
        rotationPanel.add(rotation_y);

        jLabel6.setText("Z");
        jLabel6.setOpaque(true);
        rotationPanel.add(jLabel6);

        rotation_z.setText("0");
        rotationPanel.add(rotation_z);

        rotationPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Scale"));
        rotationPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel7.setText("X");
        jLabel7.setOpaque(true);
        rotationPanel1.add(jLabel7);

        scale_x.setText("0");
        rotationPanel1.add(scale_x);

        jLabel8.setText("Y");
        jLabel8.setOpaque(true);
        rotationPanel1.add(jLabel8);

        scale_y.setText("0");
        rotationPanel1.add(scale_y);

        jLabel9.setText("Z");
        jLabel9.setOpaque(true);
        rotationPanel1.add(jLabel9);

        scale_z.setText("0");
        rotationPanel1.add(scale_z);

        jButton12.setText("Update");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(18, 18, 18))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(positionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rotationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rotationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addGap(0, 203, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12)
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jRadioButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(positionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(rotationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(rotationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel5);

        jPanel6.setOpaque(false);

        texture_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Textures"));
        texture_panel.setLayout(new java.awt.GridLayout(4, 3));

        jLabel10.setText("Colormap");
        jLabel10.setOpaque(true);
        texture_panel.add(jLabel10);

        colormap_file.setText("0");
        texture_panel.add(colormap_file);

        jButton8.setText("Browse");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        texture_panel.add(jButton8);

        jLabel11.setText("Normalmap");
        jLabel11.setOpaque(true);
        texture_panel.add(jLabel11);

        normalmap_file.setText("0");
        texture_panel.add(normalmap_file);

        jButton9.setText("Browse");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        texture_panel.add(jButton9);

        jLabel12.setText("Lightmap");
        jLabel12.setOpaque(true);
        texture_panel.add(jLabel12);

        lightmap_file.setText("0");
        texture_panel.add(lightmap_file);

        jButton10.setText("Browse");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        texture_panel.add(jButton10);

        jLabel13.setText("Bumpmap");
        jLabel13.setOpaque(true);
        texture_panel.add(jLabel13);

        bumpmap_file.setText("0");
        texture_panel.add(bumpmap_file);

        jButton11.setText("Browse");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        texture_panel.add(jButton11);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texture_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texture_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int ret = this.textureFileChooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            normalmap_file.setText(textureFileChooser.getSelectedFile().getAbsolutePath());
        }
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int ret = this.textureFileChooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            colormap_file.setText(textureFileChooser.getSelectedFile().getAbsolutePath());
        }
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int ret = this.textureFileChooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            lightmap_file.setText(textureFileChooser.getSelectedFile().getAbsolutePath());
        }
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int ret = this.textureFileChooser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            bumpmap_file.setText(textureFileChooser.getSelectedFile().getAbsolutePath());
        }
    }                                         

    private void position_xActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField bumpmap_file;
    private javax.swing.JTextField colormap_file;
    private EntityPanel entityPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField lightmap_file;
    private javax.swing.JTextField normalmap_file;
    private javax.swing.JPanel positionPanel;
    private javax.swing.JTextField position_x;
    private javax.swing.JTextField position_y;
    private javax.swing.JTextField position_z;
    private javax.swing.JPanel rotationPanel;
    private javax.swing.JPanel rotationPanel1;
    private javax.swing.JTextField rotation_x;
    private javax.swing.JTextField rotation_y;
    private javax.swing.JTextField rotation_z;
    private javax.swing.JTextField scale_x;
    private javax.swing.JTextField scale_y;
    private javax.swing.JTextField scale_z;
    private javax.swing.JFileChooser textureFileChooser;
    private javax.swing.JPanel texture_panel;
    // End of variables declaration                   
}
